### ISSUE TITLE
Add information about twitch client to the wrong version installed prompt.

### ISSUE THREAD

**Issue by julesssb** [WeakAuras/WeakAuras2#1831]
**Is your feature request related to a problem? Please describe.**
Tons of people are coming to discord/github because twitch installs the wrong addon version.

**Describe the solution you'd like**
Add a text such as 
> If you use the Twitch client to manage your AddOns, it may install the incorrect version. Please download the correct version from Curseforge.

To the message that pops up in the chat on login.

**Describe alternatives you've considered**
Can't think of anything else.

**Additional context**
https://cdn.discordapp.com/attachments/218084462523711489/648523885876215839/unknown.png

This is the message that I would adjust.

**Comment by emptyrivers** [comment]
I considered this when I implemented that warning. I decided against it, because it felt petty to specifically target twitch (even if it *is* their fault).

It’s one thing to tell people on discord that twitch is terrible, but quite another to commit that to a repository forever.

**Comment by julesssb** [comment]
Replace "Twitch" with "AddOn manager"? Should be vague enough to not step on any toes but still clear for those that actually read the message.

**Comment by emptyrivers** [comment]
Hmm, not a bad idea. I’ll think on it.

**Comment by InfusOnWoW** [comment]
@Stanzilla a quick look at the discord shows that this still happens daily. Can you ask your contacts at curse what the heck is going on?

**Comment by Stanzilla** [comment]
I do, constantly. They don't know what causes it and how to fix it. Cc @zeldokavira

**Comment by InfusOnWoW** [comment]
Well, then we should improve our in game message and tell users to contact curse support. That should help them then.
