### ISSUE TITLE
UnitFrame glows do not work sometimes even though %unit is valid

### ISSUE THREAD

**Issue by kenneth-wow** [WeakAuras/WeakAuras2#3546]
### Description

https://wago.io/QN3xUbh7

https://user-images.githubusercontent.com/16741112/159385238-7093575c-472f-496d-a686-9b082c075c1a.mp4

Converting to party, dismissing and summoning a pet, and moving players between groups sometimes causes glows to disappear even though %unit is still valid. Video and linked aura show one such example. You'll also notice Rev was inactive in party, probably trying to access raidPetN still or something? Then is not glowed when made a raid but the clone is active again

### WeakAuras Version

WeakAuras 3.7.13

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create SmartBuff - Auto Clone - Any aura that glows unitframes from %unit, pets and players enabled
2. Convert to party
3. Convert to raid

1. Create SmartBuff - Auto Clone - Any aura that glows unitframes from %unit, players enabled
2. Move players between groups a few times, making sure to have a mix of players who should be glowed or not glowed
3. Move players to G1
4. Convert to party
5. Convert to raid

Also occurs with pet summons, etc 

### Export String

!WA:2!1vv3UTTnu46Pv0g1S2uJTGH0UnVmSUUoGKM0LuGUTcy5y36o7exz5KoGn4qjszXnkrvsQeNCPrXqV2pc(6DLFek2dWbb7jipc5ID9iLC7k6p3iD4HhD(978PsHLJlJll9VZk3DL1Utz8ZxxC0oHHsI6VlloGiKuEI1uAsixeJu6d2teKb63EhLsEb(OeumnyGGNLogLqlmztNyenPHJsBItcpHCcotKFtFJkHKeWtWYreKKyCdy)cJyxLGKmqfDbxPcjunG5aB4sW8WhPFF5l4hstOYO3uTlJgtvxASKWc7WPjkH3oDAvVH36zcw61IuQu59wD1drd4Rq5R(4TVZWE(r3LS6AJrIGw5r8zloktsAzCu0uFUate14mU4rLkvYAsHI64bK0R29PzibPsJmgRYErufruu1KOtqzQiUyNutDkTfdl6IZFtFtOBU14xfzFbctZKpBEFDBiKoWE9mkEkF4tRvRXoBKDC7zrSl9yY5NeQdvnQiGr2Fzk(K6drXPmsLhyA5tu8GzZOl25tNiZ8DZNns7t8rb)bwWtlQdllRow3ELnot3FiIeeB3IVI4xeQiHULpyaruYvMIciN)0c9oZ8s6com6XhJe4kECotrtDLbigX6ff2vuRZDQUG0okr1afO4cF3QB1SxxFjjwNLURTYTx52osUqb2tdfOyZehPqwJe8d7AcRrsLduknXarOZ6LAVze20rJau2WvSHfSNIsc0978rUFT6B7v3D2ORzIoxSMgWzzXjf(1HXr4g(kDkNOw0notxc2UbmKuUiuZ2rQB1fcPKaJGlIrhKa3FKsqn9f5s3yCwYSd2Izc)5iT9mwtS0gMZfPb5R7KPtr)ug6iDftoqho)hsqmv0emXplm0G3fpSERon616u9al3KU6lOdN2Vw1UE976v117vx1rq0x52Tt9wTC1lBeP9Obck24NL3YDSrEpkwfDjh9w4HopWT5wNv0AAyAXg787wZTE9TlFW)8KYbl98BbFqjn6rXOj6jxpVwn3UoyzbFODAfmvAYDpYqv)Iv((P9v0yYStLorgHW8d)LIj(1ph8RWVbxyt4IV5EjCL3sZcVLMY(o745TtB4JHpb(SsW3dBax3g(HnHFupM3D6ag)W(ftFhze)Wt1RP9ZvgyW1rNLlNJLYPwg3B7MEnCR2U(48Bm6C7qhsycmp)d3hwyXtJOysFeJLRrUp8L2PF17VYtfKaAopi85Wx4g8YnkR0fcYKkES5B6LI1SaWoWTiJoudd3tGshT3mb4NG7l(DTT0WJCmCttl6I)pjdS80nwFTN2w8TBeV5W0V79NnZOC7RIeeDlHHpc(g9YpCxRPV2hn(Rn4WT19f4MlTim3jA8KHsWWuNGH7zFQMUIBORdYrpov1htx(De2x6NzNb70R9otUcbxtoINOHSKcy5ZMhQUl0WStb1ZFUv(thZZXMXzIgNlICc5jQ0fAiOhx5XziSHyOINh8WlFdOPn8O)vZTe7RrSDiIE6uAFOTB(VD0)BkGLH16vYt7KV3jRMGnhHhdUttlSVnhtMKLGcdjbkcwOJSPQ2xJiBn2S5MVBT0jBroGBGBvQQ1b)Sn0d2vpv7a7zdDbVZmz8RfX9NyGL1yAQu5(Px1avpG4vWoyc5FDUzlmpPyHXsZHNETxsIZdRODsLhOrHv6i4(msmCEhLUVoY0om)aOTbZ9F

**Comment by kenneth-wow** [comment]
https://user-images.githubusercontent.com/16741112/185756854-02db1c39-9f0b-4d1d-80d8-f928515bcb3e.mp4

issue is unfixed, maybe worsened in wotlk beta. 
example used for testing is a smart group glow for horn of winter missing on players and pets. you can see the text is accurate for active unitnames, but it doesnt match what glows.
https://wago.io/Lq0S2AG6T 

few things showcased in this video:
1. 0:00 not in party 
expected: both player and pet frame should glow 
actual: only pet frame glows

2. 0:06 invite emmazug to party 
expected: all three frames should glow
actual: only pet frame glows

3. 0:12 press horn of winter
expected: no frame should glow
actual: no frame glows

4. 0:15 click off horn of winter on player
expected: player frame should glow
actual: no frame glows

5. 0:35 change to raid style party frames, see if it fixes
expected: player frame should glow
actual: no frame glows

6. 0:36 press horn of winter
expected: no frame should glow
actual: no frame glows

7. 0:40 click off horn of winter on player
expected: unitframe of player should glow?
actual: no frame glows

**Comment by mrbuds** [comment]
1, 4, 5, 7 is expected as default settings for ignored frames for LibGetFrame (which weakauras doesn't change) are
```Lua
    ignorePlayerFrame = true,
    ignoreTargetFrame = true,
    ignoreTargettargetFrame = true,
    ignorePartyFrame = false,
    ignorePartyTargetFrame = true,
    ignoreFocusFrame = true,
    ignoreRaidFrame = false,
```
So player frame is always ignored (or you need a custom function to change options)
Using "Raid-Style Part Frames" for party it mostly work as expected

**Comment by kenneth-wow** [comment]
sorry about that.
https://user-images.githubusercontent.com/16741112/185760105-3e8f9d82-f069-4318-9570-5cf3f3a96c09.mp4

here's some further testing regarding converting between party and raid.
https://wago.io/flpgRifzR

it breaks at each step, but a reload fixes it.

**Comment by mrbuds** [comment]
@kenneth-wow Can you test with this change? https://github.com/mrbuds/WeakAuras2/commit/45d6b97603b2d9dfdbbb21ecce7264b80e811a23 or i can push PR to give you packaged version?

**Comment by mrbuds** [comment]
I can reproduce a bug with https://wago.io/flpgRifzR but it's not an issue with the action or glow
every has the aura (no clone should be active)
=> no clone active
=> /reload => pet's clone active
show/hide weakauras options solve it

**Comment by mrbuds** [comment]
opened https://github.com/WeakAuras/WeakAuras2/issues/3755 for this issue unrelated to glows or actions

**Comment by kenneth-wow** [comment]
Tested with that fix. Breaks if a pet is dismissed and resummoned.

https://user-images.githubusercontent.com/16741112/185761404-6ad61e3d-72bc-4ec3-8f7a-2bde194344f2.mp4

Note that the first time it breaks at 0:16 when converted to raid the problem is with the glow,
.When converting to party at 0:30 the problem is not just the glow as you can see the pet's name is no longer shown.

**Comment by kenneth-wow** [comment]
> opened #3755 for this issue unrelated to glows or actions

3x WeakAuras\WeakAuras-@project-version@.lua:3138: attempt to index field 'active_glows_hidefunc' (a nil value)
[string "@WeakAuras\WeakAuras-@project-version@.lua"]:3138: in function <WeakAuras\WeakAuras.lua:3110>
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0-38.lua"]:161: in function <...s\WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0.lua:153>
[string "@WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0-38.lua"]:176: in function <...s\WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0.lua:175>

**Comment by mrbuds** [comment]
> > opened #3755 for this issue unrelated to glows or actions
> 
> 3x WeakAuras\WeakAuras-@[project-version@.lua](mailto:project-version@.lua):3138: attempt to index field 'active_glows_hidefunc' (a nil value) [string "@WeakAuras\WeakAuras-@[project-version@.lua](mailto:project-version@.lua)"]:3138: in function <WeakAuras\WeakAuras.lua:3110> [string "=[C]"]: ? [string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:25> [string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire' [string "@WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0-38.lua"]:161: in function <...s\WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0.lua:153> [string "@WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0-38.lua"]:176: in function <...s\WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0.lua:175>

fixed in https://github.com/WeakAuras/WeakAuras2/commit/41afa99d6222c242cff3abf3d6641e973d2290de

**Comment by mrbuds** [comment]
@kenneth-wow can you test this change in `WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0.lua` https://github.com/mrbuds/LibGetFrame/commit/89a3d7248997cd868a1d778113363ccc38fef192 ?

**Comment by kenneth-wow** [comment]
> @kenneth-wow can you test this change in `WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0.lua` [mrbuds/LibGetFrame@89a3d72](https://github.com/mrbuds/LibGetFrame/commit/89a3d7248997cd868a1d778113363ccc38fef192) ?

https://user-images.githubusercontent.com/16741112/185813696-59737565-8f90-45aa-8622-aa7c3778f113.mp4

tested with 
https://github.com/mrbuds/LibGetFrame/commit/89a3d7248997cd868a1d778113363ccc38fef192

still not working, you can see both issues in this clip (working trigger + nonworking glow vs. nonworking trigger)

**Comment by mrbuds** [comment]
Remaining issue is covered by https://github.com/WeakAuras/WeakAuras2/issues/3755

**Comment by mrbuds** [comment]
Fyi @kenneth-wow next version of WeakAuras will include updated version of LibGetFrame-1.0 where i have disabled callback on UNIT_PET.
It could have lead to FPS issues for people with an UI having a very high number of frames.

You can turn on scan of frames on UNIT_PET with
```Lua
local LGF = LibStub("LibGetFrame-1.0")
LGF.TrackPets(true)
```
