### ISSUE TITLE
auras with TTS are broken

### ISSUE THREAD

**Issue by FloowC** [WeakAuras/WeakAuras2#4605]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Since patch 10.1.7 all my auras with TTS are broken. Icons and such show up but the sound is always missing. I suspect this is due to the dropdown for TTS voices being empty. Most of the time it doesn't show any items. The size of the list varies from time to time and sometimes it contains "en_US_male" and "en_US_female". Selecting either one of  them doesn't help. The aura stays silent.

@mrbuds and I have tried troubleshooting it but without any success yet. Since more people have mentioned the isssue now I suspect this is more than just a personal computer setting. Check discord "TTS voices empty" thread for steps we tried already.

### WeakAuras Version

5.7.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
no lua error
```

### Reproduction Steps

1. open WeakAuras
2. create new aura
3. go to actions
4. check on show box
5. check chat message box
6. select Text-to-speech in Message Type
7. open Voice drop down

### Last Good Version

wow patch 10.1.5

### Screenshots

voices in windows:
![voices-in-windows](https://github.com/WeakAuras/WeakAuras2/assets/83220140/713bb3dc-1239-4cc8-a2fb-6082cd3317fa)
voices in wow settings:
![voices-in-game](https://github.com/WeakAuras/WeakAuras2/assets/83220140/53596b6a-82fd-4b76-85a9-55c031aada52)
voices in WA:
https://media.discordapp.net/attachments/1149560851674697828/1149560851947335750/image.png

### Export String

```Text
!WA:2!DvvZUTTrq4iOwyav0gh1eJ(ZfHCiaPar2wi2UiO)atfPghOiPsYuNcyaPLCxsUXu7YU7slBFlcOT5SEcke6XEspc6jGqOpb(qp1t(jOZUKsXP6GWSF7m7mZ38dl1U6OQ4Q43(vZO(CMdpv4tk5ngfYp6Pt3j6S2VgDj(OLOuvex0lrr5mzfXf9ccKevP5iMpG3NtzkVMT662YEPpNhJ5JzoJPjKHlwDSfoKezPDs0eLGggseYp5bIcX3E3PPsIJc5FQC4uuQaXqJiYVyUfNrQ5erjX4fGgdKr8Xn5s1Wj6tPmQAON0yw19xQHs4Jjc1fGRNHjEPbbUGS4zT60V9l7yPVWw)8nUk3QEWLifxC)V5BVsM6roJWuoGv0ZNpO5HoUdCCp0212GpRjNHPgkiztJViaBXugxoC6Ap)Xc4YUq8pCImHehFewwXshQEjXOlicBtUvzT)6liG)SD63QtNf38nV)b7LCVBcmGxeUv)UPPScURsYDq(k6ze38ZVGJj)1TUgkjebdf)tardH8VE9PesYHqa5RSrqsenfXOJ0sS9TbYqOANTLfd47feKUwiiSqv0glXaDP1AGo3escucXYjAD0uBwDRrikdSnRE22BKTt2UznYQ7fqzuz0)h2sroxfbvgjsPFwsK4S8472Za6WMeQz3NSv2wlHJEqfkuWtz43EVKQAtH6pc6MEvr)xYNBan)fWfq2mqwiKvF667s2QlxvJW4PHr180Du5f)KnVXB2KhZfpVuPsLVkhLehyASB42RFYNAWGXaUMY8pMIvrwhchVo350Zjyd4BwMpt8ZfH4cZ9VovQObxKTXmbxbPTlaA1Tx3wzBjGevRZmJI(MOOCPN99)XMBw7w36zLNwKDqlWMTf0lR9JPimqDOAUUVhPSYJlnyJ5c8XcuYKJlewU(Dmte9EPBNJ62QGcUXCC2g5H8zuj1lMm8D25qVK8WI0BDfO6nSVic(3s)ZYWy(42cYVKsy(x0)d2PEJ9Ytv9fl0)90I2QYt0N0X0sVuLIZ6bDeWCYmnChtp49MRLxLFt1hYRwLHF61c)WkKiJMRcol9HitS4gr9pLrKYYgZD8rXKCXoua(ogVzbufre5frOHrQ3yfZr4GR8JrsjKH4b6HNh4jPSWyYFEB7rPXkAfpf8um1wz0kwAf0cjv1RhEFdhABoNRhWKAbpPzHRhDucxOMjmT)MPQkZPS8gzaPYCmvQ3DCem75949(6d29GPR7pZ2qCErc3iLINl2Vx)h(8r(hh0i5URw)QB4EkvIGkkoYESPt16soFujpjzeW427wFN67ptX9lgi)Ss)(hDFkozZxGec(yyBaU2JQ1oMBJItIqLNhiG1yWAcOvS815naT1q643ZPPDRwDn8qZIqa2lblEid9GKiGgwrqzAxbRa0RVGX(9ZE0VjGnJsuiz278QTuVbizVJ0l0cq(KtoeJ7XKNCmbD6HqxK8KxqWu0joA9KN0cmuybl7QZddNI5d8HHp(OOjGO5PIsUtHxgOuYbNXP(KpCXAii8B466mduVaBOaKn9swWwnvLShxX2FDd4m)1FwOYKv8DuJurCYxgPujYNS926pOwNY3E9xu3(GQs79QFq9DRE2F)Q)7
```

**Comment by InfusOnWoW** [comment]
Can you try the following, in chat write "/etrace"
This will open the event trace window which will show a list of events happening.
Enter "VOICE_CHAT_TTS" in the filter box.
Then run the following commands one by one, if there's any output in the event box hover it and make a screenshot. Also note whether there's any text to speech output.
/run C_VoiceChat.SpeakText(0, "Test", 0,0, 100)
/run C_VoiceChat.SpeakText(0, "Test", 1,0, 100)

**Comment by InfusOnWoW** [comment]
ny output in the event box *hover* it

**Comment by InfusOnWoW** [comment]
Can you try with the same procedure:
 /run C_VoiceChat.SpeakText(1, "Test", 1,0, 100)

**Comment by FloowC** [comment]
![grafik](https://github.com/WeakAuras/WeakAuras2/assets/83220140/259ec3c1-6c33-4cc7-8143-fcffd4554d0b)
"test" was the sound output

**Comment by mrbuds** [comment]
For reference, i asked @FloowC to edit weakauras file to try this change <https://github.com/mrbuds/WeakAuras2/commit/a5ebfb6a1a07f430ca0fa5e0fa550697fd95fdb4> but it seems it didn't result in any improvement

I suspect C_VoiceChat.GetTtsVoices() to be empty at login in conditions i can't reproduce

**Comment by InfusOnWoW** [comment]
@mrbuds I've linked two fixes that I think should fix the issue. There's a 3. issue, that is I think unrelated here: https://github.com/InfusOnWoW/WeakAuras2/commit/9c188e2935d2ff3f08dbf760ef9d82cbff7757c0.

**Comment by FloowC** [comment]
Shall I do these changes to my files locally and see if it solves anything?

**Comment by InfusOnWoW** [comment]
you can do that, or just wait a few days until it's in the alpha.

**Comment by FloowC** [comment]
Dropdown seems fixed and I can hear a lovely robotic voice. The voice names are still broken. Like en_US_female and en_US_male seems just wrong to me but I don't think it's in your power.
I will wait for the alpha and double check again.
